---
# ansible-playbook playbooks/go_build/restic.yaml -e 'playbook_hosts=localhost'
- name: execute go build restic/restic
  hosts: "{{ playbook_hosts | default('localhost') }}"
  gather_facts: false
  become: false

  tasks:
    - name: build restic/restic binary on localhost
      become: false
      ansible.builtin.import_role:
        name: go_build
      vars:
        go_build_repo_url: "https://github.com/restic/restic.git"
        go_build_repo_version: "master"
        go_build_package: "./cmd/restic"
        go_build_output_name: "restic"

    - name: copy restic binary to /usr/local/bin
      become: true
      ansible.builtin.copy:
        src: "{{ go_build_binary_path }}"
        dest: "/usr/local/bin/restic"
        mode: "0755"
        owner: root
        group: root
