---
- name: install package from PyPI or TestPyPI  # noqa: package-latest
  ansible.builtin.pip:
    name: >-
      {{ pyproject_install_package_name
         ~ ('[' ~ pyproject_install_package_extras ~ ']'
            if pyproject_install_package_extras else '') }}
    state: latest
    virtualenv: "{{ pyproject_install_venv_dir }}"
    virtualenv_command: python3 -m venv
    extra_args: "{{ _pyproject_install_pip_extra_args[pyproject_install_source] }}"
