---
namespace: ak1ra_lab
name: restic_profile
version: 0.1.0
readme: README.md
authors:
  - ak1ra <ak1ra.komj@gmail.com>
description: Profile-based restic wrapper with Ansible deployment support
license_file: LICENSE
tags:
  - storage
  - tools
  - linux
  - backup
  - restic
dependencies: {}
repository: https://github.com/ak1ra-lab/restic-profile
documentation: https://github.com/ak1ra-lab/restic-profile
homepage: https://github.com/ak1ra-lab/restic-profile
issues: https://github.com/ak1ra-lab/restic-profile/issues
# https://setuptools.pypa.io/en/latest/userguide/miscellaneous.html
manifest:
  omit_default_directives: true
  directives:
    - graft docs
    - graft playbooks
    - graft roles
    - graft src
    - graft tests
    - recursive-exclude playbooks/host_vars *
    - recursive-exclude playbooks/group_vars *
    - recursive-exclude playbooks/scripts *
    - recursive-exclude playbooks/templates *
    - recursive-exclude roles/*/molecule *
    - global-exclude *~ *.py[cod] __pycache__ *.bak *.swp *.tmp *.retry
    - include requirements.yaml LICENSE README.md pyproject.toml uv.lock zensical.toml
