---
- name: deploy systemd units for each deployment target
  ansible.builtin.include_tasks: _service_target.yaml
  loop: "{{ _restic_profile_targets }}"
  loop_control:
    loop_var: _target
    label: "{{ _target.key }}"
