---
- name: manage restic backup profiles
  hosts: "{{ playbook_hosts | default('restic_profile_nodes') }}"
  gather_facts: false
  become: true

  tasks:
    - name: apply restic_profile role
      ansible.builtin.import_role:
        name: ak1ra_lab.restic_profile.restic_profile
